version: 2.0
jobs:
  build:
    docker:
      - image: slaperche0scality/nttec:latest
    steps:
      - checkout
      - run: mkdir build && cd build && cmake -G 'Unix Makefiles' .. -DCMAKE_BUILD_TYPE=Release -DNTTEC_USE_SIMD=ON 'Unix Makefiles' .. && make
      - run: cd build && make check-format
      - run: cd build && make check-lint
      - run: cd build && make check
      # w/o SIMD
      - run: cd build && cmake .. -DNTTEC_USE_SIMD=OFF && make benchmark
      # w/ SSE4
      - run: cd build && cmake .. -DNTTEC_USE_SIMD=SSE4 && make benchmark
      # w/ AVX2
      - run: cd build && cmake .. -DNTTEC_USE_SIMD=AVX2 && make benchmark
