version: 2.0
jobs:
  build:
    docker:
      - image: slaperche0scality/nttec:latest
    steps:
      - checkout
      - run: mkdir build && cd build && cmake -G 'Unix Makefiles' .. -DCMAKE_BUILD_TYPE=Release -DNTTEC_USE_SIMD=ON 'Unix Makefiles' ..
      - run: chmod +x ../benchmark/libs/get_libs.bash && ../benchmark/libs/get_libs.bash
      - run: cd build && make
      - run: cd build && make check-format
      - run: cd build && make check-lint
      - run: cd build && make check
      - run: cd build && make benchmark
      - run: ../scripts/benchmark_all.sh benchmark/bin/Release/nttec_bench
