version: 2.0
jobs:
  build:
    docker:
      - image: slaperche0scality/quadiron:latest
    steps:
      - checkout
      - run:
          name: get other libs
          command: bash ../benchmark/libs/get_libs.bash
      - run:
          name: Compile with Clang 6 (Debug mode)
          command: >
            rm -rf build && mkdir build && cd build &&
            CXX=/usr/bin/clang++-6.0 cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug .. &&
            make
      - run:
          name: Compile with Clang 6 (Release+SIMD mode)
          command: >
            rm -rf build && mkdir build && cd build &&
            CXX=/usr/bin/clang++-6.0 cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Release -DQUADIRON_USE_SIMD=ON .. &&
            make
      - run:
          name: Compile with GCC 8 (Debug mode)
          command: >
            rm -rf build && mkdir build && cd build &&
            CXX=/usr/bin/g++-8 cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug .. &&
            make
      - run:
          name: Compile with GCC 8 (Release+SIMD mode)
          command: >
            rm -rf build && mkdir build && cd build &&
            CXX=/usr/bin/g++-8 cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Release -DQUADIRON_USE_SIMD=ON .. &&
            make
  android:
    docker:
      - image: slaperche0scality/quadiron-ndk:latest
    steps:
      - checkout
      - run:
          name: Compile on ARM64 with the NDK
          command: >
            rm -rf build && mkdir build && cd build &&
            cmake -G 'Unix Makefiles' -DCMAKE_AR=/arm64/bin/aarch64-linux-android-ar -DCMAKE_BUILD_TYPE=Debug .. &&
            make
  test:
    docker:
      - image: slaperche0scality/quadiron:latest
    steps:
      - checkout
      - run:
          name: Compilation
          command: >
            mkdir build && cd build &&
            cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Release -DQUADIRON_USE_SIMD=ON 'Unix Makefiles' .. &&
            make
      - run:
          name: Format
          command: cd build && make check-format
      - run:
          name: Lint
          command: cd build && make check-lint
      - run:
          name: Unit tests
          command: cd build && make check
      - run:
          name: Benchmark
          command: cd build && make benchmark
      - run:
          name: Comparison
          command: cd build && ../scripts/benchmark_all.sh benchmark/bin/Release/nttec_bench

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - android
      - test
